import fs from "node:fs";
import path from "node:path";

export function isHookInstalled(gitDirectory: string): boolean {
  const hookPath = path.join(gitDirectory, "hooks", "pre-commit");

  return fs.existsSync(hookPath);
}

export function installHook(
  gitDirectory: string,
): boolean {
  const hookPath = path.join(
    gitDirectory,
    "hooks",
    "pre-commit",
  );

  if (fs.existsSync(hookPath)) {
    return false;
  }

  const templatePath = path.join(
    __dirname,
    "..",
    "templates",
    "pre-commit",
  );

  fs.copyFileSync(templatePath, hookPath);
  fs.chmodSync(hookPath, 0o755);

  return true;
}
export function uninstallHook(
  gitDirectory: string,
): boolean {
  const hookPath = path.join(
    gitDirectory,
    "hooks",
    "pre-commit",
  );

  if (!fs.existsSync(hookPath)) {
    return false;
  }

  const content = fs.readFileSync(hookPath, "utf8");

  if (!content.includes("Generated by Git Blocker")) {
    return false;
  }

  fs.unlinkSync(hookPath);

  return true;
}